base_url: oncall.apatsev.org.ru
broker:
  type: rabbitmq
celery:
  worker_shutdown_interval: ""
cert-manager:
  enabled: false
database:
  type: postgresql
env:
  - name: DANGEROUS_WEBHOOKS_ENABLED
    value: 'True'
  - name: GRAFANA_CLOUD_NOTIFICATIONS_ENABLED
    value: 'False'
grafana:
  enabled: false
externalGrafana:
  url: http://grafana.apatsev.org.ru
ingress:
  annotations:
    cert-manager.io/issuer: null
    kubernetes.io/ingress.class: nginx
  enabled: true
  tls: []
ingress-nginx:
  enabled: false
mariadb:
  enabled: false
postgresql:
  auth:
    database: oncall
    existingSecret:
  enabled: true
